### ISSUE TITLE
problem with pip3 install

### ISSUE THREAD

**Issue by ds-04** [WhaleJ84/librenms_handler#126] opened 2022-10-18 15:31 UTC
This works:

``pip3 install librenms-handler==0.4.0 --user``

But the latest version has an issue. Where python 3.6.8 won't load the pip3 module.

**Comment by WhaleJ84** [comment] 2022-10-18 17:12
Is there any output you can provide so I can try to replicate on my end?

**Comment by WhaleJ84** [comment] 2022-10-18 20:55
Also, after providing error output, could you try `pip3 install --index-url https://test.pypi.org/simple/ --no-deps librenms-handler`? You should get v0.4.2 - let me know if that works.

**Comment by ds-04** [comment] 2022-10-19 07:18
> Also, after providing error output, could you try `pip3 install --index-url https://test.pypi.org/simple/ --no-deps librenms-handler`? You should get v0.4.2 - let me know if that works.

That works

`]$ pip3 install --index-url https://test.pypi.org/simple/ --no-deps librenms-handler --user`
`Collecting librenms-handler
  Downloading https://test-files.pythonhosted.org/packages/f7/4a/714161c3838d2008f103f1f506a45b8000135b43ce8eb9123ec38f1e769e/librenms_handler-0.4.2.1-py3-none-any.whl
Installing collected packages: librenms-handler
Successfully installed librenms-handler-0.4.2.1`

`]$ python3
Python 3.6.8 (default, Aug 13 2020, 07:46:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import librenms_handler`
`>>> `

**Comment by ds-04** [comment] 2022-10-19 07:22
Issue with 0.4.1 (below) but 0.4.0 is OK

`~]$ pip3 --version`
`pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)`
`~]$ pip3 install librenms-handler --user`
`Collecting librenms-handler`
 ` Downloading https://files.pythonhosted.org/packages/98/98/e87f3887c950459cb5bbcdb2b3e348f2fe4fbdf4e128ffd7e7a44527b8da/librenms_handler-0.4.1-py3-none-any.whl
Installing collected packages: librenms-handler
Successfully installed librenms-handler-0.4.1`

`~]$ python3`
`Python 3.6.8 (default, Aug 13 2020, 07:46:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import librenms_handler`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'librenms_handler'`

**Comment by WhaleJ84** [comment] 2022-10-19 18:57
`v0.4.2` has been released on pypi.org. Running `pip install --upgrade librenms-handler` should get you to the latest version. Testing on my end shows it working. Please let me know if its the same for you and I can close the issue.

**Comment by ds-04** [comment] 2022-10-27 09:13
apologies for the slow reply, it did indeed fix it.

now have an issue with self signed cert and _requests_ ... but that is not necessarily an issue for this project

**Comment by WhaleJ84** [comment] 2022-10-28 16:14
Thanks for confirming! As for the self signed cert issue, you can bypass it with the `verify=False` flag when initialising the class, but I can see from your code that you utilise this after. There are ways to use Requests with self-signed certs without disabling the verification but it is a little cumbersome and most people simply opt to disable it instead. Apologies for any inconvenience caused by the broken release - checks will be developed to catch this sooner in future.

**Closed by WhaleJ84** 2022-10-28 16:14 UTC
Labels: bug
